DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS PORTFOLIO_ITEM;

CREATE TABLE CUSTOMER (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50),
    BALANCE INT
);

CREATE TABLE PORTFOLIO_ITEM (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID INT,
    TICKER VARCHAR(10),
    QUANTITY INT,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID)
);

INSERT INTO CUSTOMER(NAME, BALANCE)
VALUES
    ('Mohamed', 10000),
    ('Ahmed', 10000),
    ('Mekky', 10000);
